### PR TITLE
Rework windows build

### PR DESCRIPTION
**Pull request by adament**
According to upstream https://github.com/lballabio/QuantLib/issues/1552 build_shared_libs is not supported on Windows, so build a static QuantLib library but use the dynamic runtime so the library can be used with python.

Furthermore use an out-of-source build directory as done in the upstream documentation https://www.quantlib.org/install/cmake.shtml this results in a correctly generated quantlib.hpp file so there is no need to replace it in the quantlib-python recipe.

Furthermore I enabled building the test suite on Windows and running the tests in the test step similar to on Unix.

I also used ninja as the build tool on Windows because it was significantly faster on my local machine and allowed faster testing.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by adament** [comment]
@conda-forge-admin, please restart ci

**Comment by adament** [comment]
@timkpaine do you have time to look at this? If this is merged I would like to make sure my changes for building quantlib-python on windows also work on the conda-forge infrastructure.

**Comment by timkpaine** [comment]
@adament it will take a few hours for the build to propagate to prod but then you can pickup the PR on the other repo

**Comment by adament** [comment]
Thank you!

**Pull request merged**
